### ISSUE TITLE
change UUID?

### ISSUE THREAD

**Issue by Alexander-Barth** [TEOS-10/GibbsSeaWater.jl#1]
Right now TEOS-10/GibbsSeaWater.jl and kouketsu/GSW.jl have the same UUID. Could this lead to a problem? I think it would be saver to use a different UUID to avoid any problems if users have TEOS-10/GibbsSeaWater.jl and kouketsu/GSW.jl installed. But, I guess, changing the UUID would mean that users would have to reinstall TEOS-10/GibbsSeaWater.jl.

**Comment by kouketsu** [comment]
I would like to change UUID in kouketsu/GSW.jl. Someone who has installed GSW.jl might have to reinstall, but GSW.jl will not be updated and I think the users of GSW.jl had better to go GibbsSeaWater.jl.

**Comment by Alexander-Barth** [comment]
OK, thanks! We can leave the UUID for GibbsSeaWater.jl, then.
