### ISSUE TITLE
Official Listing on teos-10.org

### ISSUE THREAD

**Issue by PaulMBarker** [TEOS-10/GibbsSeaWater.jl#13]
Hi,

I am about to update the teos10 software page http://www.teos-10.org/software.htm

I will be adding links for the python and R version of GSW, would you also like a link? If so how would you like it to appear? it does not have to be a button as I have currently used,  it can be how you prefer, a paragraph under its own heading  etc.

Paul.

**Comment by kouketsu** [comment]
@PaulMBarker Thank you for the information

I would like to see a link to GibbsSeaWater.jl on the official site. 
I like the list (for each language) of simple links with a library name like:

### Julia
* [GibbsSeaWater.jl](https://github.com/TEOS-10/GibbsSeaWater.jl))

But, I respect your decision.
