### ISSUE TITLE
Drop support for julia 0.6 and 0.7?

### ISSUE THREAD

**Issue by Alexander-Barth** [TEOS-10/GibbsSeaWater.jl#2]
Do you all agree to drop support for julia version 0.6 and 0.7 and concentrate on the current versions 1.0 and 1.3 ?

**Comment by dankelley** [comment]
I think that's a good plan.

**Comment by ax1ine** [comment]
I'd also drop any unsupported versions of Julia.

**Comment by Alexander-Barth** [comment]
Thanks for your feedback!
