### ISSUE TITLE
Should we remove Manifest.toml?

### ISSUE THREAD

**Issue by Alexander-Barth** [TEOS-10/GibbsSeaWater.jl#21]
The repository now includes a Project.toml (supported with the version range of dependencies) and a Manifest.toml (specific version of the complete dependency tree). Given the discussion [here](https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029) and [here](https://stackoverflow.com/questions/58996197/when-should-a-julia-project-have-a-manifest-and-project-file) I am wondering if we  should not remove the Manifest.toml to reduce the potential of versioning conflicts.

**Comment by dankelley** [comment]
The links you provide suggest not to include `Manifest.toml`. 

These files are generated by Julia, as is indicated by their first lines. Generally, my git policy is to avoid including such files in any sort of project, Julia or not.  By analogy, in a C/C++ based project, we would not include `.o` files, which are generated by the compiler.  A problem with including such things in a repo is that the developers might start receiving some ill-thought-out pull requests, as novice users might think that changes ought to be transmitted back upstream.

It's pretty easy to add it back to the repo, if problems arise.

**Comment by kouketsu** [comment]
Thank you for the suggestion & comments.
I deleted Manifest.toml to try it out.
