### ISSUE TITLE
GibbsSeaWater on Mac M1

### ISSUE THREAD

**Issue by thomasfrederikse** [TEOS-10/GibbsSeaWater.jl#22]
I am trying to run GibbsSeaWater.jl on Julia 1.8 (Native Mac M1 version). but when I run a function, for example
```
gsw_p_from_z(-10,50)
```
I get the following error:
```
ERROR: could not load library "/Users/tfrederi/.julia/packages/GibbsSeaWater/vq3GE/deps/usr/lib/libgswteos-10.dylib"
dlopen(/Users/tfrederi/.julia/packages/GibbsSeaWater/vq3GE/deps/usr/lib/libgswteos-10.dylib, 0x0001): tried: '/Users/tfrederi/.julia/packages/GibbsSeaWater/vq3GE/deps/usr/lib/libgswteos-10.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

It seems to me as if the underlying dynamic library still uses x86 instead of ARM. When I install GibbsSeaWater from PKG, the pre-compilation of BinaryProvider fails, which might be related.

I am using GibbsSeaWater v0.1.1 [9a22fb26] 

Thanks!

Thomas

**Comment by haakon-e** [comment]
It seems like #20 has fixed this issue.

Any chance someone could push a minor release to this package? @kouketsu, @Alexander-Barth?

In the meantime I'll clone the repo and use the local version for my work.

**Comment by kouketsu** [comment]
Thank you.
I have bumped the version.
