### ISSUE TITLE
Compat bump?

### ISSUE THREAD

**Issue by willcoxe** [TEOS-10/GibbsSeaWater.jl#25]
Can we bump Compat to a higher version? 

Right now this package is blocking any DataFrames.jl package more recent than v0.21 and several others. I have tested whether at least my code using GSW still works on a repo clone with Compat set to include '4' and for me nothing breaks (but I have not tested all functions, just the ones I use).

Thanks in advance!

**Comment by Alexander-Barth** [comment]
Dear @kouketsu, I just had the the same issue. I think we can remove the dependency to Compat. All test continue to work:

https://github.com/TEOS-10/GibbsSeaWater.jl/actions/runs/3732882897

Can you merge the PR https://github.com/TEOS-10/GibbsSeaWater.jl/pull/28 if you agree?

**Comment by kouketsu** [comment]
Thanks @Alexander-Barth.
I've merged it.

Please check as
`pkg> add GibbsSeaWater#master`

I will bump version after solving some other issues (around the beginning of next year).
