### ISSUE TITLE
v0.1.3 result in significant version regression for many dependencies

### ISSUE THREAD

**Issue by truedichotomy** [TEOS-10/GibbsSeaWater.jl#32]
I just installed the released v0.1.3 and that resulted in version regression in many Julia packages. When installing directly from the Master, the packages update to much more current versions.

**Comment by Alexander-Barth** [comment]
Note that version v0.1.3 was not released due to a failing test. If somebody can have a look which dependency are outdated, that would be useful. Maybe it is just a matter of rebuilding the jll.

**Comment by Alexander-Barth** [comment]
v0.1.3 has only been released now. I guess you installed v0.1.2. Please re-open if the issue persists with the complete screen output .
