### ISSUE TITLE
continous integration

### ISSUE THREAD

**Issue by Alexander-Barth** [TEOS-10/GibbsSeaWater.jl#5]
It would be nice to add contiguous integration  (travis CI, appveyor) to GibbsSeaWater.jl but I do not think that I have sufficient rights to do so.
There are already the necessary configuration files in the repo (.travis.yml and appveyor.yml), but the repo owner should enable CI by adding this repo to https://travis-ci.org and https://ci.appveyor.com/ (one can use the GitHub account for these sites). 

Maybe @PaulMBarker or @efiring can help us here?

**Comment by PaulMBarker** [comment]
Do you need more permissions on the TEOS-10 github repository, so you can do this?

**Comment by Alexander-Barth** [comment]
Yes, I think only somebody with the ownership permission of a repo can do this [1]. (I do not have this right).

I can trigger Appeveor (CI on Windows) manually, but it does not run automatically on every commit. I think these services require Webhooks to run automatically, available in Settings -> Wehbooks. The settings tab is not visible to me.

[1] https://docs.travis-ci.com/user/tutorial/

**Comment by PaulMBarker** [comment]
I think you should have access to it now. Let me know if you don't.

**Comment by Alexander-Barth** [comment]
Thanks a lot for your trust! Travis CI and appveyor run now on every commit!
